@Host = localhost:9090

### JobService health
GRPC {{Host}}/grpc.health.v1.Health/Check

### Get a list of all jobs
GRPC {{Host}}/JobService/ListJobs

### Get a list of jobs matching the filter
GRPC {{Host}}/JobService/ListJobs
Content-Type: application/json

{
  "filter": "title==^*leg*;salary>100;status==Active"
}

### Get a single job with id 1
GRPC {{Host}}/JobService/GetJob
Content-Type: application/json

{
  "id": 1
}
