@Host = https://localhost:7267

### Get a list of all jobs
GET {{Host}}/jobs


###
GET https://localhost:7267/jobs?filter=(title=='^*hkhk*' or description=='^*hkhk*')
accept: text/plain

###
POST {{Host}}/jobapplications/apply
Content-Type: application/json

{
  "jobId": 1,
  "jobSeekerId": 1
}

###
POST {{Host}}/auth/login
Content-Type: application/json

{
  "email": "michael.jensen@yahoo.com",
  "password": "upt2zv5kt"
}